name: dictionary

on:
  pull_request:
    branches: master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout implementation
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: run check
        run: python tools/checker.py
